"""add ai metrics

Revision ID: 003
Revises: 002
Create Date: 2026-09-24 12:21:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '003'
down_revision = '001'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('ai_tokens_prompt', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('ai_tokens_completion', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('ai_cost_usd', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('ai_latency_ms', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('ai_model_used', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'ai_model_used')
    op.drop_column('analyses', 'ai_latency_ms')
    op.drop_column('analyses', 'ai_cost_usd')
    op.drop_column('analyses', 'ai_tokens_completion')
    op.drop_column('analyses', 'ai_tokens_prompt')
    # ### end Alembic commands ###
