"""Add security_findings

Revision ID: 23a1c5e43b36
Revises: 004
Create Date: 2026-09-24 19:18:56.753123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a1c5e43b36'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_repo_pr'), table_name='analyses')
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyses_repo'), 'analyses', ['repo'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_analyses_repo'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.create_index(op.f('ix_analyses_repo_pr'), 'analyses', ['repo', 'pr_number'], unique=False)
    # ### end Alembic commands ###
